### PR TITLE
Fix Github Actions and pre-commit

### PR DESCRIPTION
**Pull request by pganssle**
For some reason pylint was broken on my installation, so I had to bump the version.

GHA requires pinning to an older version of Ubuntu in order to run tests on Python 3.6.

### CODE REVIEW

**Comment by andersk** [comment]
GitHub dropped Python 3.6 from [`windows2022`](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) and [`macos-11`](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md) as well; you’d need to go back to [`windows2019`](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md) and [`macos-10.15`](https://github.com/actions/runner-images/blob/main/images/macos/macos-10.15-Readme.md) for that.

(I doubt 3.6 support is worthwhile anymore—who is going to be upgrading backports.zoneinfo if they’re still on Python 3.6?—but your call.)

**Comment by andersk** [comment]
`.github/workflows/build-publish.yml` is going to need similar changes.

**Comment by hugovk** [comment]
Please see https://github.com/pganssle/zoneinfo/pull/128 to update this PR. It doesn't fix everything but moves things in the right direction.

**Comment by pganssle** [comment]
OK, this version is fully working, but it's kind of a big monolith, and I'd like to be able to individually link to PRs that fixed some of the user facing-ish changes in the changelog, so I'm going to break it up into smaller PRs that won't pass CI until the end, I think.

**Pull request merged**
